kill:
  name: kill
  selfAllow: false
  sentences:
  - "%author% killed %victim%'s butt"
  - "%author% murdered %victim% \U0001F52A"
  - "%victim% was killed by %author%"
  - "%victim% was slained by %author%'s power"
  - "%victim% fell out of the world \U0001F573"
  - "%victim% didn't want to live the same world as %author%"
  selfPing:
  - "%author% are you ok?"
  - "%author% do you need help?"
  - "%author% there's something is wrong with your brain!"
  - "%author% is a bit stupid \U0001F60F"
  - "%author% no, I will never do that!"
  sources:
  - https://media4.giphy.com/media/yNFjQR6zKOGmk/giphy.gif
  - https://media2.giphy.com/media/RLi2oeVZiVkE8/giphy.gif
  - https://media1.giphy.com/media/x88yuKqdpWbC0/giphy.gif
  - https://media0.giphy.com/media/3o6Zt2wf1yKWucbkqY/giphy.gif
  - https://media4.giphy.com/media/Z5zuypybI5dYc/giphy.gif
  - https://media2.giphy.com/media/u8maN0dMhVWPS/giphy.gif
  - https://media1.tenor.com/images/c4ff93caa999d6332d74035324a36f52/tenor.gif
  - https://media1.tenor.com/images/65eb11d03b956948b6e52f4b1875129f/tenor.gif
hug:
  name: hug
  selfAllow: false
  sentences:
  - "%author% don't squish %victim% hard!"
  - "%author% hugs %victim%!"
  - "%author% executed a command gave %victim% hug 999"
  - "%victim% got a huge hug from %author% \U0001F60A"
  selfPing:
  - I'll do it for you %author%
  - "%author% How do you hug your self?"
  - "%author% are you sad right now?"
  - "I feel sad for %author% \U0001F622"
  sources:
  - https://media1.tenor.com/images/a36ff6478946d33cd63c3a737f025355/tenor.gif
  - https://media1.tenor.com/images/0228777b26293c96b3e55aded5f9e8a3/tenor.gif
  - https://media1.tenor.com/images/11bb43404d06d1adabd683953fd8e294/tenor.gif
  - https://media1.tenor.com/images/2eb0f4ff9d564481b6f6a486a2c25b3b/tenor.gif
  - https://media1.tenor.com/images/5d9bac65ddad0e6dc836d9e8d07c77c4/tenor.gif
  - https://media1.tenor.com/images/3c83525781dc1732171d414077114bc8/tenor.gif
  - https://media1.tenor.com/images/d2a2b216ef3bc74406f661049f937999/tenor.gif
  - https://media1.tenor.com/images/c67e9d0cf6b9126540c4e490bacbceee/tenor.gif
  - https://media1.tenor.com/images/7822479112cf7625937e8c56ff5824b4/tenor.gif
cuddle:
  name: cuddle
  selfAllow: false
  sentences:
  - "%author% cuddles %victim%"
  - "%victim% was squished hard by %author% \U0001F601"
  - "%victim% and %author% is so sweet \U0001F60D"
  - "%victim% did you know this is how my mom and dad met each other ❕"
  selfPing:
  - I'll cuddle you %author%
  - "%author% let me think!"
  - "%author% is single?"
  - "%author% let me find your partner \U0001F50E"
  sources:
  - https://media1.tenor.com/images/7321887a0c12baab747ed998f253a38c/tenor.gif
  - https://media1.tenor.com/images/0c5e9c64bda27902f8199c0a00cf1e6a/tenor.gif
  - https://media1.tenor.com/images/85f48bfe2846e8cad93009ca8dba0e9a/tenor.gif
  - https://media1.tenor.com/images/20600fb0fb700d65b8fe70883e629d37/tenor.gif
  - https://media1.tenor.com/images/08de7ad3dcac4e10d27b2c203841a99f/tenor.gif
  - https://media1.tenor.com/images/c9e2e21f4eedd767a72004e4ab521c9d/tenor.gif
  - https://media1.tenor.com/images/4aa41fac755715a687f68a6319d885eb/tenor.gif
  - https://media1.tenor.com/images/a6bb91e588aa461110476df4d3986efd/tenor.gif
  - https://media1.tenor.com/images/2ec5516cb05f48c9f2d8d5bc20f95c41/tenor.gif
  - https://media1.tenor.com/images/e07473d3cf372dbc24c760527740b85e/tenor.gif
kiss:
  name: kiss
  selfAllow: false
  sentences:
  - "%author% kisses %victim%"
  - "%author% kisses %victim%'s lips"
  - I feel %author%'s love for %victim%
  - "%author% want to kiss %victim%'s lips in real life?"
  - "%author% shows love for %victim% \U0001F495"
  selfPing:
  - "%author% want to kiss your arms?"
  - "I'll kiss you %author% \U0001F48B"
  - "%author% is searching for kisses"
  - "/give %author% kiss 64 \U0001F60F"
  sources:
  - https://media1.tenor.com/images/31362a548dc7574f80d01a42a637bc93/tenor.gif
  - https://media1.tenor.com/images/015c71df440861e567364cf44e5d00fe/tenor.gif
  - https://media1.tenor.com/images/b1189e353db0bed3521885bec284264b/tenor.gif
  - https://media1.tenor.com/images/5922f11cb8aa9b0afec277029c9f2852/tenor.gif
  - https://media1.tenor.com/images/6921951f1e034ceb3d08e50f2e50967d/tenor.gif
  - https://media1.tenor.com/images/b4e22911641a1a233508ae8a19445505/tenor.gif
  - https://media1.tenor.com/images/09914c0ecfe0677e843af2d547f342cf/tenor.gif
  - https://media1.tenor.com/images/2f23c53755a5c3494a7f54bbcf04d1cc/tenor.gif
  - https://media1.tenor.com/images/7fd98defeb5fd901afe6ace0dffce96e/tenor.gif
  - https://media1.tenor.com/images/d307db89f181813e0d05937b5feb4254/tenor.gif
  - https://media1.tenor.com/images/d0cd64030f383d56e7edc54a484d4b8d/tenor.gif
  - https://media1.tenor.com/images/558f63303a303abfdddaa71dc7b3d6ae/tenor.gif
  - https://media1.tenor.com/images/8cab4f4c73547d077c56066461c40a5e/tenor.gif
pat:
  name: pat
  selfAllow: false
  sentences:
  - "%author% pets %victim%! How sweet <3"
  - "%author% pets %victim%'s big forehead"
  - "%author% pets %victim%! I hope %victim% too"
  - "%author% smoothly pets %victim%"
  selfPing:
  - "I'll do it for you %author% \U0001F600"
  - "I'm a bot but I feel sad for you %author% \U0001F614"
  - I'll ask someone to do that for you %author%
  sources:
  - https://media1.tenor.com/images/e01e09d8e27c7247314b3dd611f47007/tenor.gif
  - https://media1.tenor.com/images/fd7365b518ee53285f39ef8b1caf5b6e/tenor.gif
  - https://media1.tenor.com/images/be0c22e0af951aa7fa8753381663eb2c/tenor.gif
  - https://media1.tenor.com/images/857aef7553857b812808a355f31bbd1f/tenor.gif
  - https://media1.tenor.com/images/bfdeb9ec7f89aad86170d06fe4189bec/tenor.gif
  - https://media1.tenor.com/images/005e8df693c0f59e442b0bf95c22d0f5/tenor.gif
  - https://media1.tenor.com/images/54722063c802bac30d928db3bf3cc3b4/tenor.gif
  - https://media1.tenor.com/images/3df4f9e7067a651640251d5f6d764ad2/tenor.gif
  - https://media1.tenor.com/images/116fe7ede5b7976920fac3bf8067d42b/tenor.gif
lick:
  name: lick
  selfAllow: false
  sentences:
  - "%author% licks %victim%"
  selfPing:
  - "%author% licks %author%... \U0001F615"
  sources:
  - https://media1.tenor.com/images/371964995d70b3f03cc60e6e45b91e3d/tenor.gif
  - https://media1.tenor.com/images/463cc8ccecc67effa7d320876aaa6781/tenor.gif
  - https://media1.tenor.com/images/c1d9ff6f013a3deba4b7941fa00374e5/tenor.gif
  - https://media1.tenor.com/images/5f73f2a7b302a3800b3613095f8a5c40/tenor.gif
slap:
  name: slap
  selfAllow: false
  sentences:
  - "%author% slaps %victim%'s face! Ouch \U0001F629"
  - "%author% slaps %victim%'s big forehead!"
  - "%author% slaps %victim%!"
  selfPing:
  - "Slap yourself %author%? Why? \U0001F914"
  - Tell me why %author%!?
  - I'll slap you now %author%!
  sources:
  - https://media1.tenor.com/images/0720ffb69ab479d3a00f2d4ac7e0510c/tenor.gif
  - https://media1.tenor.com/images/df8af24e5756ecf4a4e8af0c9ea6499b/tenor.gif
  - https://media1.tenor.com/images/18b77174c2a50dc305bf18da4a208e6a/tenor.gif
  - https://media1.tenor.com/images/0860d681fbe7ad04a2f39735ab939176/tenor.gif
  - https://media1.tenor.com/images/d14969a21a96ec46f61770c50fccf24f/tenor.gif
  - https://media1.tenor.com/images/dcd359a74e32bca7197de46a58ec7b72/tenor.gif
  - https://media1.tenor.com/images/37c72d1a4a4ad8108897642f7bebc4be/tenor.gif
punch:
  name: punch
  selfAllow: false
  sentences:
  - "%author% gives %victim% a punch! \U0001F44A"
  - "%author% punches %victim%'s face! \U0001F616"
  - "%author% gives %victim% a punch!"
  - "%author% punches %victim%'s face!"
  selfPing:
  - "%author% you know what! I'll do it for you bitch!"
  - "I'm asking someone to punch and shake %author%'s head \U0001F609"
  - "%author% was slained by %author%'s punch! Hmmn... something is wrong \U0001F914"
  - I can puch %author% if you want
  sources:
  - https://media1.tenor.com/images/df8af24e5756ecf4a4e8af0c9ea6499b/tenor.gif
  - https://media1.tenor.com/images/2595f11a72e4285d71450ab5a9bc42d5/tenor.gif
  - https://media1.tenor.com/images/82ff489bd6f5f0466610cbdb6d210f8f/tenor.gif
  - https://media1.tenor.com/images/5757920ac53ad76009c2f83b154e62a3/tenor.gif
  - https://media1.tenor.com/images/8b41214d214bdd9e19b1cfc9fb2c9d0b/tenor.gif
  - https://media1.tenor.com/images/8789543a04274a720b13b1af69a25867/tenor.gif
bite:
  name: bite
  selfAllow: false
  sentences:
  - ''
  selfPing:
  - ''
  sources: []
wave:
  name: wave
  selfAllow: false
  sentences:
  - ''
  selfPing:
  - ''
  sources: []
greet:
  name: greet
  selfAllow: false
  sentences:
  - ''
  selfPing:
  - ''
  sources: []
choke:
  name: choke
  selfAllow: false
  sentences:
  - ''
  selfPing:
  - ''
  sources: []
