Bubble gum is pink because that was the only food dye available in the factory where it was made.:
  source: ''
A group of clowns is sometimes called a giggle.:
  source: ''
According to a poll of 11,000 Americans, 84 percent of vegetarians and vegans return to eating meat.:
  source: ''
When it comes to wine, an aroma similar to cat pee is a considered a good thing.:
  source: ''
The Spangler Candy Company chose to name their famous lollipops “Dum Dums” because it was a word that was easy for any kid to say.:
  source: ''
The Margherita pizza was named after Margherita of Savoy, Queen consort of Italy from 1878 to 1900.:
  source: ''
Chock Full o' Nuts coffee does not contain nuts. It's named for a chain of nut stores that the founder converted into coffee shops.: 
  source: ''
Goldfish can distinguish the music of one composer from another.:
  source: ''
Tsundoku is the act of acquiring books or other reading materials and not reading them.:
  source: ''
Blood donors in Sweden receive a thank you text when their blood is used.:
  source: ''
During WWII, La-Z-Boy manufactured seats for tanks, torpedo boats, gun turrets, and armored cars.:
  source: ''
The first Macy's Thanksgiving Day Parade featured lions, camels, and elephants from the Central Park Zoo.:
  source: ''
The feral puppies in Chernobyl are radioactive.:
  source: ''
The term “lawn mullet” means having a neatly manicured front yard and an unmowed mess in the back.:
  source: ''
When a man allegedly found a dead mouse in his can of Mountain Dew, Pepsi had an expert claim in an affidavit that the drink was so acidic it would have dissolved the mouse after 30 days.: 
  source: ''
Wyoming is home to only two escalators.:
  source: ''
Continental plates drift as fast as fingernails grow.:
  source: ''
Many people are either right- or left-eared and eyed in the same way we're right- or left-handed.:
  source: ''
Novelist Patricia Highsmith kept about 300 snails as pets. She carried them in her handbag to parties.:
  source: ''
In the 18th century, wealthy British landowners hired ornamental hermits to live in their gardens.:
  source: ''
Lobsters' bladders are in their heads.:
  source: ''
A butt is a real unit of measurement for a cask of wine. A buttload is about 108 Imperial gallons.:
  source: ''
